# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sanjoy Roy
title-bn: সঞ্জয় রায়
email: info@sanjoyroy.com
phone: +91-9830446591
intro-len: 300

tagline: 'Technologist and Entrepreneur: "Where the mind is without fear and the head is held high..."'
tagline-bn: 'প্রযুক্তিবিদ এবং উদ্যোক্তা: "চিত্ত যেথা ভয়শূন্য, উচ্চ যেথা শির,..."'

recent-title: Recent Posts
recent-title-bn: সর্বশেষ পোস্ট
archived-title: Archived Posts
archived-title-bn: আর্কাইভ পোস্ট
readmore-title: Read More
readmore-title-bn: বিস্তারিত


keywords: >- # this means to ignore newlines until "keywords2:"
  My name is Sanjoy Roy. I am based in Kolkata, India. I am a 
  Microsoft Certified Information Technologist and 
  an Entrepreneur specialised in Health Informatics with 19 years 
  of expertise in Healthcare and Education Domain. I have keen 
  interest in Technology, Travelling, History, Mythology,
  Politics, Social Systems, Education, Rural Development etc.

keywords-bn: >- # this means to ignore newlines until "baseurl:"
  Sanjoy, Sanjay, Sanjaya, Roy, Ray, Religion, Spiritual, Hinduism, Buddism, KarmaYoga, Karma Yoga, KarmYog, KarmaYog,
  Moksha, Salvation, Freedom, Soul, Jyan yoga, Bhakti yoga, Nishkam Karma, Computer, 
  Software, Website, Digital, Marketing, Technology, LAN, WAN, CCTV, Solar, Healthcare, 
  Health Informatics, Vanaprashta, Senior Citizen, Old age home.


description: > # this means to ignore newlines until "description_bn:"
  My name is Sanjoy Roy. I am based in Kolkata, India. I am a 
  Microsoft Certified Information Technologist and 
  an Entrepreneur specialised in Health Informatics with 20 years 
  of expertise in Healthcare and Education Domain. I have keen 
  interest in Technology, Travelling, History, Mythology,
  Politics, Social Systems, Education, Rural Development etc.

description-bn: > # this means to ignore newlines until "baseurl:"
  আমার নাম সঞ্জয় রায়। আমি কোলকাতা-কেন্দ্রিক একজন মাইক্রোসফট সার্টিফায়েড তথ্য 
  প্রযুক্তিবিদ এবং একজন উদ্যোক্তা । আমি স্বাস্থ্য তথ্যবিজ্ঞানে  একজন বিশেষজ্ঞ । আমি গত ২০ বছর 
  ধরে তথ্য প্রযুক্তিতে কাজ করছি । বিশেষত হেলথ কেয়ার এবং 
  শিক্ষা ডোমেইনে । আমার আগ্রহের বিষয় হল প্রযুক্তি, ভ্রমণ, ইতিহাস, পুরাণ, রাজনীতি, সামাজিক ব্যবস্থা, 
  শিক্ষা, পল্লী উন্নয়ন ইত্যাদি। 

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title.html

# for sass file minification
sass:
  style: compressed

defaults:
-
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts" # previously `post` in Jekyll 2.2.
  values:
    layout: "post"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
